spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      group-id: demo-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        group.instance.id: "1"
        spring.json.trusted.packages: "com.chamath.kafka_playground.section07"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
